"""remove report status

Revision ID: 25ca9322dbf3
Revises: 4bb6e17da635
Create Date: 2026-01-10 22:10:01.710044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ca9322dbf3'
down_revision: Union[str, None] = '4bb6e17da635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='reports_status_pkey'),
    sa.UniqueConstraint('name', name='reports_status_name_key')
    )
    # ### end Alembic commands ###
