"""initial

Revision ID: 4bb6e17da635
Revises: d17577f764ce
Create Date: 2026-01-10 22:03:12.351105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb6e17da635'
down_revision: Union[str, None] = 'd17577f764ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reports_status_id_fkey', 'reports', type_='foreignkey')
    op.drop_column('reports', 'status_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('reports_status_id_fkey', 'reports', 'reports_status', ['status_id'], ['id'])
    # ### end Alembic commands ###
